// this is the shape the data should be saved on Async Storage
export default [
	{
		StudentNo: "XXXXXXXXXX",
		SchoolCode: "TGE",
		LastName: "ADELEMI",
		FirstName: "JANET",
		OtherName: "IJEOMA",
		Gender: "Female",
		DateOfBirth: "1998-10-05",
		NationalityID: 156,
		StateOfOriginID: 2388,
		LGAOfOriginID: 3,
		AdmissionDate: "2020-10-05",
		ClassAdmittedID: 5,
		TermAdmitted: 2,
		YearOfAdmission: 2014,
		CurrentClassID: 5,
		GuardianFirstName: "JOHN",
		GuardianLastName: "UGBOEFI",
		GuardianOtherName: "CHUKWUEMEKA",
		GuardianGender: "Male",
		GuardianPhoneNo: "23480544555",
		GuardianEmailAddress: "john.ubo@gmail.com",
		GuardianRelationship: "Uncle",
		GuardianAddress: "3 Oweka Road",
		status: "UPLOADED",
		ImageData: require('../assets/images/student.jpg'),
		id: 1
	},
	{
		StudentNo: "XXXXXXXXXX",
		SchoolCode: "TGE",
		LastName: "Amaka",
		FirstName: "Ikenna",
		OtherName: "IJEOMA",
		Gender: "Female",
		DateOfBirth: "1998-10-05",
		NationalityID: 156,
		StateOfOriginID: 2388,
		LGAOfOriginID: 3,
		AdmissionDate: "2020-10-05",
		ClassAdmittedID: 5,
		TermAdmitted: 2,
		YearOfAdmission: 2014,
		CurrentClassID: 5,
		GuardianFirstName: "JOHN",
		GuardianLastName: "UGBOEFI",
		GuardianOtherName: "CHUKWUEMEKA",
		GuardianGender: "Male",
		GuardianPhoneNo: "23480544555",
		GuardianEmailAddress: "john.ubo@gmail.com",
		GuardianRelationship: "Uncle",
		GuardianAddress: "3 Oweka Road",
		status: "UPLOADED",
		ImageData: require('../assets/images/student4.jpg'),
		id: 2
	},
	{
		StudentNo: "XXXXXXXXXX",
		SchoolCode: "TGE",
		LastName: "Chizoba",
		FirstName: "Ikenna",
		OtherName: "Alisca",
		Gender: "Male",
		DateOfBirth: "1998-10-05",
		NationalityID: 156,
		StateOfOriginID: 2388,
		LGAOfOriginID: 3,
		AdmissionDate: "2020-10-05",
		ClassAdmittedID: 5,
		TermAdmitted: 2,
		YearOfAdmission: 2014,
		CurrentClassID: 5,
		GuardianFirstName: "JOHN",
		GuardianLastName: "UGBOEFI",
		GuardianOtherName: "CHUKWUEMEKA",
		GuardianGender: "Male",
		GuardianPhoneNo: "23480544555",
		GuardianEmailAddress: "john.ubo@gmail.com",
		GuardianRelationship: "Uncle",
		GuardianAddress: "3 Oweka Road",
		status: "UPLOADED",
		ImageData: require('../assets/images/student4.jpg'),
		id: 3
	},
	{
		StudentNo: "XXXXXXXXXX",
		SchoolCode: "TGE",
		LastName: "Chizoba",
		FirstName: "Ikenna",
		OtherName: "Alisca",
		Gender: "Male",
		DateOfBirth: "1998-10-05",
		NationalityID: 156,
		StateOfOriginID: 2388,
		LGAOfOriginID: 3,
		AdmissionDate: "2020-10-05",
		ClassAdmittedID: 5,
		TermAdmitted: 2,
		YearOfAdmission: 2014,
		CurrentClassID: 5,
		GuardianFirstName: "JOHN",
		GuardianLastName: "UGBOEFI",
		GuardianOtherName: "CHUKWUEMEKA",
		GuardianGender: "Male",
		GuardianPhoneNo: "23480544555",
		GuardianEmailAddress: "john.ubo@gmail.com",
		GuardianRelationship: "Uncle",
		GuardianAddress: "3 Oweka Road",
		status: "UPLOADED",
		ImageData: require('../assets/images/student4.jpg'),
		id: 4
	},
	{
		StudentNo: "XXXXXXXXXX",
		SchoolCode: "TGE",
		LastName: "Chizoba",
		FirstName: "Ikenna",
		OtherName: "Alisca",
		Gender: "Male",
		DateOfBirth: "1998-10-05",
		NationalityID: 156,
		StateOfOriginID: 2388,
		LGAOfOriginID: 3,
		AdmissionDate: "2020-10-05",
		ClassAdmittedID: 5,
		TermAdmitted: 2,
		YearOfAdmission: 2014,
		CurrentClassID: 5,
		GuardianFirstName: "JOHN",
		GuardianLastName: "UGBOEFI",
		GuardianOtherName: "CHUKWUEMEKA",
		GuardianGender: "Male",
		GuardianPhoneNo: "23480544555",
		GuardianEmailAddress: "john.ubo@gmail.com",
		GuardianRelationship: "Uncle",
		GuardianAddress: "3 Oweka Road",
		status: "UPLOADED",
		ImageData: require('../assets/images/student4.jpg'),
		id: 5
	},
	{
		StudentNo: "XXXXXXXXXX",
		SchoolCode: "TGE",
		LastName: "Chizoba",
		FirstName: "Ikenna",
		OtherName: "Alisca",
		Gender: "Male",
		DateOfBirth: "1998-10-05",
		NationalityID: 156,
		StateOfOriginID: 2388,
		LGAOfOriginID: 3,
		AdmissionDate: "2020-10-05",
		ClassAdmittedID: 5,
		TermAdmitted: 2,
		YearOfAdmission: 2014,
		CurrentClassID: 5,
		GuardianFirstName: "JOHN",
		GuardianLastName: "UGBOEFI",
		GuardianOtherName: "CHUKWUEMEKA",
		GuardianGender: "Male",
		GuardianPhoneNo: "23480544555",
		GuardianEmailAddress: "john.ubo@gmail.com",
		GuardianRelationship: "Uncle",
		GuardianAddress: "3 Oweka Road",
		status: "UPLOADED",
		ImageData: require('../assets/images/student4.jpg'),
		id: 6
	},
	{
		StudentNo: "XXXXXXXXXX",
		SchoolCode: "TGE",
		LastName: "Chizoba",
		FirstName: "Ikenna",
		OtherName: "Alisca",
		Gender: "Male",
		DateOfBirth: "1998-10-05",
		NationalityID: 156,
		StateOfOriginID: 2388,
		LGAOfOriginID: 3,
		AdmissionDate: "2020-10-05",
		ClassAdmittedID: 5,
		TermAdmitted: 2,
		YearOfAdmission: 2014,
		CurrentClassID: 5,
		GuardianFirstName: "JOHN",
		GuardianLastName: "UGBOEFI",
		GuardianOtherName: "CHUKWUEMEKA",
		GuardianGender: "Male",
		GuardianPhoneNo: "23480544555",
		GuardianEmailAddress: "john.ubo@gmail.com",
		GuardianRelationship: "Uncle",
		GuardianAddress: "3 Oweka Road",
		status: "UPLOADED",
		ImageData: require('../assets/images/student3.jpg'),
		id: 7
	}
];

// store shap
/**
 * uploaded_students: {
 * 	student_id: {<payload>}
 * }
 * waiting_students: {
 * 	proposedID: {<payload>}
 * }
 */